# Generated by Django 5.2.7 on 2025-12-03 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_jobapplication_status'),
        ('vacancies', '0016_jobpost_vacancies_j_created_e7dcff_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant', '-created_at'], name='application_applica_fc9296_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job_post', '-created_at'], name='application_job_pos_754fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status'], name='application_status_e72231_idx'),
        ),
    ]
