services:
  - type: web
    name: headhunter-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 3
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: headhunter-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend.vercel.app,https://your-frontend.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://your-frontend.vercel.app,https://your-frontend.onrender.com"
      - key: STATIC_URL
        value: "/static/"
      - key: MEDIA_URL
        value: "/media/"
databases:
  - name: headhunter-db
    plan: starter
