# Generated by Django 5.2.4 on 2025-08-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_post_comments_count_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shares_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
