# Generated by Django 5.2.4 on 2025-07-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_latitude_customuser_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='work_hours_per_week',
            field=models.CharField(blank=True, help_text="Masalan: 'Более 30 часов в неделю'", max_length=50, null=True),
        ),
    ]
