# Generated by Django 5.2.4 on 2025-07-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='salary_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ish haqi (USD)', max_digits=10, null=True),
        ),
    ]
