# Generated by Django 5.2.4 on 2025-07-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
