# Generated by Django 5.2.7 on 2025-12-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_certificate_accounts_ce_user_id_390047_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='workexperience',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
