# Generated by Django 5.2.7 on 2025-12-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_workexperience_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={},
        ),
    ]
