# Generated by Django 5.2.4 on 2025-08-10 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_banner_company_description_companyphoto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyfollow',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='companyfollow',
            index=models.Index(fields=['company', 'user'], name='companies_c_company_782adb_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfollow',
            index=models.Index(fields=['user'], name='companies_c_user_id_e922ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyfollow',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='uniq_company_user_follow'),
        ),
    ]
