# Generated by Django 5.2.7 on 2025-12-03 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companyfollow_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['owner'], name='companies_c_owner_i_f8927e_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='companies_c_name_2d8260_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['-created_at'], name='companies_c_created_a89ef1_idx'),
        ),
    ]
