-- +goose Up

-- One conversation per application: the seeker on one side, the hiring company (any of
-- its members) on the other. Only people already connected by an application can talk,
-- which keeps the chat free of cold spam.
CREATE TABLE conversations (
    id              uuid PRIMARY KEY DEFAULT uuidv7(),
    application_id  uuid        NOT NULL UNIQUE REFERENCES applications (id) ON DELETE CASCADE,
    company_id      uuid        NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    seeker_id       uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    vacancy_id      uuid        NOT NULL REFERENCES vacancies (id) ON DELETE CASCADE,
    last_message_id bigint,
    last_message_at timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX conversations_seeker_idx ON conversations (seeker_id, (COALESCE(last_message_at, created_at)) DESC, id DESC);
CREATE INDEX conversations_company_idx ON conversations (company_id, (COALESCE(last_message_at, created_at)) DESC, id DESC);

CREATE TYPE message_kind AS ENUM ('text', 'image', 'file', 'voice', 'location');

CREATE TABLE messages (
    id              bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    conversation_id uuid         NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
    sender_id       uuid         REFERENCES users (id) ON DELETE SET NULL,
    kind            message_kind NOT NULL,
    body            text         NOT NULL DEFAULT '',   -- text, or caption for attachments
    file_id         uuid         REFERENCES files (id) ON DELETE SET NULL,
    meta            jsonb        NOT NULL DEFAULT '{}', -- location: {lat, lng, name}
    -- Generated by the client for optimistic UI; resending the same id is a no-op.
    client_id       uuid         NOT NULL,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    deleted_at      timestamptz,
    UNIQUE (sender_id, client_id)
);
CREATE INDEX messages_conversation_idx ON messages (conversation_id, id DESC);

-- Per-user read position (each company member keeps their own).
CREATE TABLE conversation_reads (
    conversation_id uuid   NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
    user_id         uuid   NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    last_read_id    bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (conversation_id, user_id)
);

-- +goose Down
DROP TABLE IF EXISTS conversation_reads;
DROP TABLE IF EXISTS messages;
DROP TYPE IF EXISTS message_kind;
DROP TABLE IF EXISTS conversations;
