# Generated by Django 5.2.4 on 2025-08-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
    ]
