# Generated by Django 5.2.4 on 2025-08-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_jobpost_is_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='stars_given',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
