# Generated by Django 5.2.4 on 2025-08-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_jobpost_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
