# Generated by Django 5.2.4 on 2025-08-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
