# Generated by Django 5.2.4 on 2025-08-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_jobpost_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='plan',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Pro', 'Pro'), ('Premium', 'Premium')], max_length=50, null=True),
        ),
    ]
