# Generated by Django 5.2.4 on 2025-08-09 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_banner_company_description_companyphoto_and_more'),
        ('vacancies', '0009_alter_jobpost_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(
                to='companies.company',
                on_delete=models.CASCADE,
                related_name='job_posts',
                null=True,
                blank=True,
            ),
        ),

    ]
