# Generated by Django 5.2.4 on 2025-08-09 03:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_banner_company_description_companyphoto_and_more'),
        ('vacancies', '0010_jobpost_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(
                to='companies.company',
                on_delete=models.CASCADE,
                related_name='job_posts',
                null=True,
                blank=True,
            ),
        ),
        # va yulduzlar uchun alter bo‘lsa o‘z holicha qolsin

        migrations.AlterField(
            model_name='jobpostrating',
            name='stars',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
