# Generated by Django 5.2.4 on 2025-08-20 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_populate_jobpost_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
