# Generated by Django 5.2.7 on 2025-10-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
