# Generated by Django 5.2.7 on 2025-12-03 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_companies_c_owner_i_f8927e_idx_and_more'),
        ('vacancies', '0015_jobpost_is_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['-created_at'], name='vacancies_j_created_e7dcff_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['employer', '-created_at'], name='vacancies_j_employe_540457_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['company', '-created_at'], name='vacancies_j_company_dff1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['is_draft', 'is_filled', '-created_at'], name='vacancies_j_is_draf_9ef8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['plan'], name='vacancies_j_plan_56ac24_idx'),
        ),
    ]
